version: '2'

services:
    db:
        image: mysql:5.7
        volumes:
            - "./.data/db:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: "Abc123"
            MYSQL_DATABASE: "sms_service"
            MYSQL_USER: "farzaneh"
            MYSQL_PASSWORD: "Abc123"
    php:
        build:
            context: php7-fpm
            args:
                TIMEZONE: "Asia/Tehran"
        volumes:
            - /${SYMFONY_APP_PATH}/sms_simulator:/var/www/symfony
            - /${SYMFONY_APP_PATH}/sms_provider:/var/www/symfony2
            - ./logs/symfony:/var/www/symfony/app/logs
    nginx:
        build: nginx
        ports:
            - 80:80
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx
    nginx2:
        build: nginx/sender1
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx
    nginx3:
        build: nginx/sender2
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx
    
    redis:
        image: redis:latest

